services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8080:80'     # Cambiado
      - '8443:443'    # Cambiado
      - '8181:81'
    volumes:
      - ./nginx-data:/data
      - ./nginx-letsencrypt:/etc/letsencrypt
      - ./nginx-snippets:/snippets:ro
    environment:
      TZ: 'Europe/Berlin'
    extra_hosts:
      - "host.docker.internal:host-gateway"
